### ISSUE TITLE
Failed to load the save-session package

### ISSUE THREAD

**Issue by njuarezgt** [mpeterson2/save-session#141]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: elementary OS
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.15.7

### Stack Trace

Failed to load the save-session package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/njuarez/.atom/packages/save-session-master/lib/save-session.coffee:1:7)
    at Object.<anonymous> (/home/njuarez/.atom/packages/save-session-master/lib/save-session.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:761:34)
    at /usr/share/atom/resources/app.asar/src/package.js:192:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:169:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:183:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:405:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:369:14)
    at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom.js:667:21)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:82:25)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:35:9)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Gabriel-p** [comment]
Failed to load the save-session package
1. Open Atom.

**Atom Version**: 1.6.0
**System**: elementary OS
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.16.0

### Stack Trace

Failed to load the save-session package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/media/rest/Dropbox/apps_sync/Atom/.atom/packages/save-session/node_modules/atom-space-pen-views/lib/main.js:4:10)
    at Object.<anonymous> (/media/rest/Dropbox/apps_sync/Atom/.atom/packages/save-session/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/media/rest/Dropbox/apps_sync/Atom/.atom/packages/save-session/lib/save-session.coffee:4:7)
    at Object.<anonymous> (/media/rest/Dropbox/apps_sync/Atom/.atom/packages/save-session/lib/save-session.coffee:45:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app.asar/src/package.js:720:27)
    at /opt/atom/resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/opt/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/opt/atom/resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/opt/atom/resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/opt/atom/resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/opt/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///opt/atom/resources/app.asar/static/index.js:86:5)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "linter-python-pep8",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-css",
      "language-gfm",
      "language-go",
      "language-hyperlink",
      "language-java",
      "language-javascript",
      "language-json",
      "language-less",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-property-list",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-source",
      "language-sql",
      "language-toml",
      "language-xml",
      "language-yaml"
    ]
  },
  "save-session": {
    "dataSaveFolder": "/home/gabriel/.atom/packages/save-session/projects"
  }
}
```

### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
feedback, v0.38.0
highlight-selected, v0.11.1
linter, v1.11.3
linter-pep8, v1.0.1
linter-pylint, v1.2.0
minimap, v4.19.0
minimap-git-diff, v4.1.8
monokai, v0.18.0
save-session, v0.16.0
script-runner, v1.8.4

# Dev
No dev packages
```
