### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Foadsf** [mpeterson2/save-session#160]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.16.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22%2FUsers%2Ffoobar%2FDownloads%22%5D%2C%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Ffoobar%2FDownloads%2F10.1007%252F978-3-540-74658-4_25.bib%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22__CF_USER_TEXT_ENCODING%22%3A%220x1F5%3A0x0%3A0x0%22%2C%22TMPDIR%22%3A%22%2Fvar%2Ffolders%2F70%2Fqsmqvzwj41q_nk6k7__2k79h0000gn%2FT%2F%22%2C%22HOME%22%3A%22%2FUsers%2Ffoobar%22%2C%22SHELL%22%3A%22%2Fusr%2Flocal%2Fbin%2Fbash%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.ay6FLUjtoG%2FListeners%22%2C%22Apple_PubSub_Socket_Render%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.R5Stxjoy6v%2FRender%22%2C%22DISPLAY%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.zKjUHGVCCG%2Forg.macosforge.xquartz%3A0%22%2C%22PATH%22%3A%22%2Fusr%2Fbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fsbin%22%2C%22LOGNAME%22%3A%22foobar%22%2C%22XPC_SERVICE_NAME%22%3A%22com.apple.xpc.launchd.oneshot.0x1000003f.Atom%22%2C%22COMMAND_MODE%22%3A%22unix2003%22%2C%22USER%22%3A%22foobar%22%2C%22XPC_FLAGS%22%3A%220x0%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22ATOM_HOME%22%3A%22%2FUsers%2Ffoobar%2F.atom%22%7D%2C%22appVersion%22%3A%221.13.0%22%2C%22atomHome%22%3A%22%2FUsers%2Ffoobar%2F.atom%22%2C%22shellLoadTime%22%3A300%7D:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /Users/foobar/.atom/packages/save-session/lib/files.coffee:14:26
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "linter-mixed-indent",
      "linter-shellcheck",
      "linter-scspell",
      "linter-write-good"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "save-session": {
    "dataSaveFolder": "/Users/foobar/.atom/packages/save-session/projects"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (inactive)
atom-ctags, v5.0.0 (active)
autocomplete-clang, v0.10.0 (active)
autocomplete-fortran, v0.9.1 (active)
bottom-dock, v0.4.4 (active)
build, v0.67.0 (active)
build-cmake, v0.8.2 (active)
build-make, v0.13.0 (active)
build-tools, v4.5.7 (active)
build-xcodebuild, v0.2.0 (active)
busy, v0.7.0 (active)
clipboard-plus, v0.5.1 (active)
color-picker, v2.2.3 (active)
dash, v1.7.0 (inactive)
file-icons, v2.0.8 (active)
git-control, v0.8.2 (inactive)
git-log, v0.4.1 (active)
git-plus, v7.1.0 (active)
git-time-machine, v1.5.4 (inactive)
glowing-cursor, v0.1.1 (active)
highlight-selected, v0.11.2 (active)
ink, v0.6.2 (active)
intentions, v1.1.2 (active)
language-d, v3.3.1 (inactive)
language-fortran, v2.0.17 (inactive)
language-glsl, v2.0.1 (inactive)
language-julia, v0.10.0 (inactive)
language-latex, v1.0.0 (inactive)
language-lisp, v0.2.0 (inactive)
language-opencl, v0.1.1 (inactive)
language-rust, v0.4.8 (inactive)
latex, v0.42.0 (inactive)
latex-completions, v0.3.2 (active)
latexer, v0.3.0 (active)
linter, v1.11.21 (active)
linter-chktex, v1.3.0 (active)
linter-clang, v3.4.4 (active)
linter-cppcheck, v0.2.1 (active)
linter-cpplint, v1.0.1 (active)
linter-gcc, v0.6.15 (active)
linter-gfortran, v0.2.2 (active)
linter-manager, v0.2.12 (active)
linter-mixed-indent, v1.1.0 (inactive)
linter-rust, v0.7.2 (active)
linter-scspell, v2.2.0 (inactive)
linter-shellcheck, v1.4.3 (inactive)
linter-write-good, v0.8.0 (inactive)
markdown-pdf, v1.5.0 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.26.5 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
multi-cursor, v2.1.5 (inactive)
open-recent, v5.0.0 (active)
pigments, v0.38.0 (active)
platformio-ide-terminal, v2.2.2 (active)
rulerz, v0.4.1 (active)
save-session, v0.16.0 (active)
todo-show, v1.9.0 (inactive)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (active)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by ethikz** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package 0.15.7


### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22%2FUsers%2FJosh%2FDevelopment%2Fcom.liferay.portal.plugins.sdk-7.0%2Fhooks%2Ftile-hook%2Fdocroot%2FWEB-INF%2Fjsps%2Fhtml%2Ftaglib%2Fui%2Ftile%22%5D%2C%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22__CF_USER_TEXT_ENCODING%22%3A%220x1F6%3A0x0%3A0x0%22%2C%22TMPDIR%22%3A%22%2Fvar%2Ffolders%2F5g%2Ffndj31f11pjcgksfw56g7mnr0000gp%2FT%2F%22%2C%22HOME%22%3A%22%2FUsers%2FJosh%22%2C%22SHELL%22%3A%22%2Fbin%2Fzsh%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.gQ3BiJyOUK%2FListeners%22%2C%22Apple_PubSub_Socket_Render%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.LHhoa6TmtK%2FRender%22%2C%22PATH%22%3A%22%2Fusr%2Fbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fsbin%22%2C%22LOGNAME%22%3A%22Josh%22%2C%22XPC_SERVICE_NAME%22%3A%22com.apple.xpc.launchd.oneshot.0x1000000c.Atom%22%2C%22COMMAND_MODE%22%3A%22unix2003%22%2C%22USER%22%3A%22Josh%22%2C%22XPC_FLAGS%22%3A%220x0%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22ATOM_HOME%22%3A%22%2FUsers%2FJosh%2F.atom%22%7D%2C%22appVersion%22%3A%221.14.3%22%2C%22atomHome%22%3A%22%2FUsers%2FJosh%2F.atom%22%2C%22shellLoadTime%22%3A370%7D:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /packages/save-session/lib/files.coffee:14:26
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

### Commands

```
     -1:32.6.0 command-palette:toggle (atom-pane.pane.active)
     -1:27.5.0 editor:consolidate-selections (input.hidden-input)
     -1:27.5.0 core:cancel (input.hidden-input)
     -1:00.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.29.13 
atom-handlebars 1.3.0 
atom-jade 0.3.0 
autoprefixer 3.3.0 
code-peek 1.4.11 
docblockr 0.8.5 
editorconfig 1.4.1 
emmet 2.4.3 
git-blame 0.4.11 
git-plus 5.17.1 
hbs-beautify 0.1.0 
highlight-selected 0.11.2 
jade-beautify 0.1.5 
language-slim 0.5.0 
markdown-preview-plus 2.4.0 
merge-conflicts 1.4.4 
minimap 4.25.0 
open-recent 5.0.0 
perfectionist 1.2.0 
pigments 0.35.3 
platformio-ide-terminal 2.2.0 
save-session 0.15.7 
ScssBundle 0.5.0 
set-syntax 0.3.0 
seti-ui 1.3.2 
synced-sidebar 0.4.3 
todo-show 1.7.0 
vim-mode 0.65.1 
```
