### ISSUE TITLE
Uncaught TypeError: this.promptToSaveItem(...).then is not a function

### ISSUE THREAD

**Issue by karlhorky** [mpeterson2/save-session#163]
As per @Ben3eeE, copied from @masajene's original issue atom/atom#15205:

Atom: 1.19.0 x64
Electron: 1.6.9
OS: Mac OS X 10.12.6
Thrown From: Atom Core

### Stack Trace

Uncaught TypeError: this.promptToSaveItem(...).then is not a function

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:709

TypeError: this.promptToSaveItem(...).then is not a function
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:709:52)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:683:18)
    at Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1703:48)
    at HTMLElement.core:close (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:233:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:02.1.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-html-preview 0.1.22 
atom-jade 0.3.0 
atom-jshint 2.0.0 
atom-terminal-panel 4.4.4 
atom-typescript 11.0.6 
autocomplete-paths 1.0.5 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.3 
coffee-compile 0.26.0 
color-picker 2.2.5 
docblockr 0.11.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.10 
goto-definition 1.3.4 
highlight-selected 0.13.1 
intentions 1.1.5 
japanese-menu 1.13.0 
japanese-wrap 0.2.7 
linter 2.2.0 
linter-coffeelint 1.2.1 
linter-jshint 3.1.5 
linter-php 1.3.2 
linter-phpmd 1.5.3 
linter-ui-default 1.6.3 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.5 
merge-conflicts 1.4.5 
minimap 4.29.3 
minimap-autohide 0.10.1 
pretty-json 1.6.4 
project-manager 3.3.5 
sass-autocompile 0.13.3 
save-session 0.16.0 
tag 0.5.0 
terminal-plus 0.14.5 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
tool-bar-markdown-writer 0.3.0 
```

**Comment by karlhorky** [comment]
@Creky and I were also having this issue.

**Comment by lbineau** [comment]
+1

**Comment by will-ashworth** [comment]
I'm also having this issue. Noticed it over the past couple of weeks.

**Comment by uchuugaka** [comment]
This has been persistent for a good long while.

**Comment by adamlwgriffiths** [comment]
It's a sad statement about the ecosystem, when my primary text editor breaks itself every few days. Seriously guys...

**Comment by bjrmatos** [comment]
@adamlwgriffiths just uninstall the package, as the README says, the functionality is already built-in in atom, i can confirm that.. uninstall it solved the problem for me and everything is working as before.

**Comment by karlhorky** [comment]
Yeah, maybe this package should be unpublished / deleted. Or at least for versions later than the Atom where it's available in core (if that's even possible?)

**Comment by bjrmatos** [comment]
i guess it is possible by specifying some kind of metadata to `engines.atom` but it would require a maintainer interaction which it is likely not gonna happen because the maintainer seems inactive on github for a while.

**Comment by uchuugaka** [comment]
I think I did eventually, in my quest to purge things that were perf issues.

**Comment by adamlwgriffiths** [comment]
I did manually uninstall it when I figured out it was a package.
Usability is really important, and part of that is ensuring a seamless, error-free, experience. But issues like this leave a sour taste in my mouth. Manually updating and managing applications that should be self-managing is the reason I ditched Linux long ago.
