### ISSUE TITLE
Uncaught TypeError: invalid options argument

### ISSUE THREAD

**Issue by akivagold** [mpeterson2/save-session#168]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package 0.16.0

### Stack Trace

Uncaught TypeError: invalid options argument

```
At C:\Users\akiva\.atom\packages\save-session\node_modules\mkdirp\lib\opts-arg.js:13

TypeError: invalid options argument
    at optsArg (/packages/save-session/node_modules/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/packages/save-session/node_modules/mkdirp/index.js:11:10)
    at Object.save (/packages/save-session/lib/files.coffee:34:5)
    at /packages/save-session/lib/files.coffee:67:24
```

### Commands

```
  2x -1:50.9.0 window:increase-font-size (div.panels-item)
     -1:43.6.0 core:paste (input.hidden-input)
  2x -1:30 core:backspace (input.hidden-input)
     -0:16.8.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
kite 0.198.0 
language-docker 1.1.8 
save-session 0.16.0 
```

**Comment by ranjithkoolath** [comment]
Atom version: 1.54.0
save-session version: 0.15.7

I am getting the below exception:

`C:\Users\iam.root\.atom\packages\save-session\node_modules\mkdirp\lib\opts-arg.js:13
Hide Stack Trace
TypeError: invalid options argument
    at optsArg (C:\Users\iam.root\.atom\packages\save-session\node_modules\mkdirp\lib\opts-arg.js:13:11)
    at mkdirp (C:\Users\iam.root\.atom\packages\save-session\node_modules\mkdirp\index.js:11:10)
    at Object.save (file:///C:/Users/iam.root/.atom/packages/save-session/lib/files.coffee:34:5)
    at file:///C:/Users/iam.root/.atom/packages/save-session/lib/files.coffee:67:24`

**Comment by Zethrus** [comment]
I am getting this every time I try to save files in Atom.
```/Users/zethrus/.atom/packages/save-session/node_modules/mkdirp/lib/opts-arg.js:13
Hide Stack Trace
TypeError: invalid options argument
    at optsArg (/Users/zethrus/.atom/packages/save-session/node_modules/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/Users/zethrus/.atom/packages/save-session/node_modules/mkdirp/index.js:11:10)
    at Object.save (/Users/zethrus/.atom/packages/save-session/lib/files.coffee:34:5)
    at /Users/zethrus/.atom/packages/save-session/lib/files.coffee:67:24```

**Comment by picorealm** [comment]
I got this error too.  I noticed that the save folder ~/.atom/packages/save-session/projects did not exist so I manually created it.  But the error still occurs and nothing is being written to the projects folder.  Platform is Windows 10 x64

TypeError: invalid options argument
    at optsArg (C:\Users\pico\.atom\packages\save-session\node_modules\mkdirp\lib\opts-arg.js:13:11)
    at mkdirp (C:\Users\pico\.atom\packages\save-session\node_modules\mkdirp\index.js:11:10)
    at Object.save (file:///C:/Users/pico/.atom/packages/save-session/lib/files.coffee:34:5)
    at file:///C:/Users/pico/.atom/packages/save-session/lib/files.coffee:67:24

**Comment by Zethrus** [comment]
> ~/.atom/packages/save-session/projects

Creating that did not help for me, same error:

```
/home/zethrus/.atom/packages/save-session/node_modules/mkdirp/lib/opts-arg.js:13
Hide Stack Trace
TypeError: invalid options argument
    at optsArg (/home/zethrus/.atom/packages/save-session/node_modules/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/home/zethrus/.atom/packages/save-session/node_modules/mkdirp/index.js:11:10)
    at Object.save (/home/zethrus/.atom/packages/save-session/lib/files.coffee:34:5)
    at /home/zethrus/.atom/packages/save-session/lib/files.coffee:67:24
```

**Comment by picorealm** [comment]
In case anyone is interested in helping debug this issue,  notice that in `projects/save-session/lib/save-session.coffee` under the config: stanza there are multiple items: `restoreOpenFileContents`, `skipSavePrompt`, `extraDelay`, and `dataSaveFolder`.  Each of these items has a `default:` value except for `dataSaveFolder`.  

However also notice that in .atom/config.cson there is a section for the save-session package:

```cson
"save-session":
    dataSaveFolder: "C:\\Users\\pico\\.atom\\packages\\save-session\\projects"
    extraDelay: 600
    skipSavePrompt: false
```

**Comment by picorealm** [comment]
I did some console logging and what I've figured out so far: 

In /packages/save-session/files.coffee the statement:
```coffee
 Mkdirp folder, (err) =>
     Fs.writeFile(file, JSON.stringify(buffers))
```
is calling the const function `mkdirp` in `packages/save-session/node_modules/mkdirp/index.js`.

`mkdirp` accepts two parameters, `path` and `opts`.  The `path` parameter being sent from `packages/save-session/lib/files.coffee` should be `C:\Users\pico\.atom\packages\save-session\projects` and the `opts` parameter is:

```javascript
function(err) {
          return Fs.writeFile(file, JSON.stringify(buffers));
        }
```

The value for `file` should be `C:\Users\pico\.atom\packages\save-session\projects\project.json` and the value for JSON.stringify(buffers) for some sample text looks like:
[{"text":"ljlklj","diskText":""}]

So does anyone have a guess what is going on here?  It looks like `mkdirp` function in `packages/save-session/node_modules/mkdirp/index.js` is never actually running because it's choking on one of the parameters.

**Comment by picorealm** [comment]
Another update: 
In `packages/save-session/node_modules/mkdirp/lib/opts-arg.js`
the `optsArg` function gets called.  Based on the value of `opts` that is passed to it it goes through the following conditionals:
```javascript
  if (!opts)
    opts = { mode: 0o777, fs }
  else if (typeof opts === 'object')
    opts = { mode: 0o777, fs, ...opts }
  else if (typeof opts === 'number')
    opts = { mode: opts, fs }
  else if (typeof opts === 'string')
    opts = { mode: parseInt(opts, 8), fs }
  else
    throw new TypeError('invalid options argument')
```

The value of `opts` that actually gets passed to it is:
```javascript
function(err) {
      return Fs.writeFile(file, JSON.stringify(buffers));
}
```

and that value is failing all the conditional checks and reaching the final `else` statement and throwing an error because `typeof opts` is a function.

**Comment by picorealm** [comment]
I don't think this package is even necessary.  It's functionality is already included in Atom by default.  In Settings -> Core Settings uncheck "Open Empty Editor on Start" and set "Restore Previous Windows on Start" to "Always".  Then go into Settings -> Packages and search for autosave.  Go to its settings and check Enabled.

Also, restore will not work in Atom unless at least one Project has been added to the Project pane.  You can add anything there.  I just added my Documents folder.  This behavior has been filed as a bug with Atom but apparently they did not change it.

**Comment by ranjithkoolath** [comment]
works like a charm!!!!

I followed the below steps as @picorealm mentioned:
 In Settings -> Core Settings uncheck "Open Empty Editor on Start" and set "Restore Previous Windows on Start" to "Always". Then go into Settings -> Packages and search for autosave. Go to its settings and check Enabled.
 
 Thanks alot.

**Comment by Zelirian** [comment]
My _environment_:
**Atom**: 1.60.0-beta0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version (windows 10)
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package 0.15.7

Great analy @picorealm !!!

but sadly, your solution didn't work for me.

So, I edited:
`...\.atom\packages\save-session\node_modules\mkdirp\lib\mkdirp-manual.js`
line 15, from
```js
  return opts.mkdirAsync(path, opts).then(() => made || path, er => {
    if (er.code === 'ENOENT')
      return mkdirpManual(parent, opts)
        .then(made => mkdirpManual(path, opts, made))
    if (er.code !== 'EEXIST' && er.code !== 'EROFS')
      throw er
    return opts.statAsync(path).then(st => {
      if (st.isDirectory())
        return made
      else
        throw er
    }, () => { throw er })
  })
```
to
```js
  try {
    return opts.mkdirAsync(path, opts).then(() => made || path, er => {
      if (er.code === 'ENOENT')
      return mkdirpManual(parent, opts)
      .then(made => mkdirpManual(path, opts, made))
      if (er.code !== 'EEXIST' && er.code !== 'EROFS')
      throw er
      return opts.statAsync(path).then(st => {
        if (st.isDirectory())
        return made
        else
        throw er
      }, () => { throw er })
    })
  } catch (e) {
    console.error(e);
  }
```
and
`...\.atom\packages\save-session\node_modules\mkdirp\index.js`
line 11, from
```js
  opts = optsArg(opts)
```
to
```js
  try {
    opts = optsArg(opts)
  } catch (e) {
    console.error(e);
  }
```

I am aware that this is ONLY A TEMPORARY SOLUTION of the relatively dangerous, currently I do not fully know the context and purpose of this call made in this way.

At least, I can use Atom, at the moment everything seems to work, without that constant error popup.

If any problems arise, the first thing to do is to remove these changes.
