### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by victorhooi** [mpeterson2/save-session#34]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.11.0

### Steps To Reproduce

1. Attempt to close a file in Atom.
2. His yes in the do you want to save changes prompt. This error then came up.

### Stack Trace

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:490

TypeError: undefined is not a function
  at Object.module.exports.Pane.promptToSaveItem [as defaultSavePrompt] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:490:23)
  at Pane.promptToSaveItem (/Users/victorhooi/.atom/packages/save-session/lib/save-prompt.coffee:21:15)
  at Pane.module.exports.Pane.destroyItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:442:18)
  at Pane.module.exports.Pane.destroyActiveItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:422:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/workspace.js:604:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/workspace.js:643:21)
  at atom-workspace.atom.commands.add.core:close (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/workspace-element.js:284:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by mpeterson2** [comment]
Is this still an issue?

**Comment by chetmurphy** [comment]
No.

**Comment by mpeterson2** [comment]
Okay cool. Going to close this than.
