### ISSUE TITLE
Uncaught Error: Could not resolve 'autocomplete-paths' to a package path

### ISSUE THREAD

**Issue by MiincGu** [mpeterson2/save-session#42]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.11.2

### Stack Trace

Uncaught Error: Could not resolve 'autocomplete-paths' to a package path

```
At /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:347

Error: Could not resolve 'autocomplete-paths' to a package path
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:347:15)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:409:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:295:19
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:582:13
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:690:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:564:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:190:14)
  at Object.module.exports.config (/Users/MiincGu/.atom/packages/save-session/lib/config.coffee:94:19)
  at Object.module.exports.project (/Users/MiincGu/.atom/packages/save-session/lib/config.coffee:47:6)
  at Object.module.exports.save (/Users/MiincGu/.atom/packages/save-session/lib/project.coffee:15:12)
  at /Users/MiincGu/.atom/packages/save-session/lib/project.coffee:32:8
  at handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -0:01.1 project-manager:toggle (input.hidden-input)
     -0:00.0 core:confirm (input.hidden-input)
```

### Config

```
{
  "save-session": {
    "project": "/Users/MiincGu/Dropbox/DEV/Private/ToolKit"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-gocode, v0.5.0
autocomplete-plus, v1.1.0
autocomplete-snippets, v0.3.2
color, v0.5.0
compass, v0.7.5
emmet, v2.3.0
project-manager, v1.14.1
save-session, v0.11.2
seti-syntax, v0.2.1
seti-ui, v0.5.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by mpeterson2** [comment]
Not really sure what's causing this. Is it still happening?

**Comment by mpeterson2** [comment]
Going to close this.
