### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by EndorSimpkins** [mpeterson2/save-session#56]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.1
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.11.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:511

TypeError: undefined is not a function
  at Object.module.exports.Pane.promptToSaveItem [as defaultSavePrompt] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:511:23)
  at Pane.promptToSaveItem (/Users/CaninMacBook/.atom/packages/save-session/lib/save-prompt.coffee:21:15)
  at Pane.module.exports.Pane.destroyItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:456:18)
  at Pane.module.exports.Pane.destroyActiveItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:436:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/workspace.js:716:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/workspace.js:760:21)
  at atom-workspace.atom.commands.add.core:close (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/workspace-element.js:292:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:16.1 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "save-session": {
    "project": "/Users/CaninMacBook/Dropbox/Spring15/EconDev/Project/templates",
    "windowX": -19,
    "windowY": 57,
    "windowWidth": 1276,
    "windowHeight": 635,
    "dataSaveFolder": "/Users/CaninMacBook/.atom/packages/save-session/projects"
  }
}
```

### Installed Packages

```coffee
# User
save-session, v0.11.3
script-runner, v1.7.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by mpeterson2** [comment]
I'm not really sure how to reproduce this one. I don't ever get this issue.

**Comment by Tonkonozhenko** [comment]
Also got this

**Comment by bobsoppe** [comment]
The same error occurred with me when I was saving a simple HTML document

**Comment by aethant** [comment]
I get this issue when I have an untitled document open, and attempt to do a save and close (i.e. - I use the keyboard to close the tab, prompts to save and I say yes.)

I have to save the document, then request tab close.

Also have save-session installed, and the error message references the package.

**Comment by cblaupanda** [comment]
I can confirm what the previous commenter said. It happens to me when I try to close a windows and it prompts me to save. After clicking save, it throws the error. I am also using save-session

**Comment by undefVariable** [comment]
I believe "save-session" is causing this?

**Comment by const314** [comment]
I came across the same behavior as @cblaupanda

**Comment by robertbaker** [comment]
Same as @cblaupanda

**Comment by dwnnis** [comment]
same as @cblaupanda. I use save-session as well.

**Comment by mcortinas** [comment]
Same as @cblaupanda

**Comment by mpeterson2** [comment]
I think this is an unfixable error at the moment. The code that disables the prompt to save is very hacky and this issue may have to do with how fast this happens, compared to when Atom shows that message ([see here](https://github.com/mpeterson2/save-session/blob/master/lib/save-prompt.coffee#L9-L23)). Unfortunately, I don't think there is any other way to disable it at the moment.

**Comment by mpeterson2** [comment]
Closing old issues that are probably irrelevant to the code just to clear up the clutter. Go ahead and open a new issue if there is still a problem.
