### ISSUE TITLE
Uncaught SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by matttbe** [mpeterson2/save-session#58]
Hello,

Thank you for developing this Atom plugin!

I had this error with the latest version of save-session and when starting Atom. Note during my previous session, I closed all tabs.

**Atom Version**: 0.176.0
**System**: linux 3.18.0-12-generic
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.11.3

### Stack Trace

Uncaught SyntaxError: Unexpected string

```
At file:///opt/atom/resources/app/static/index.html?loadSettings=%7B%22bootstrapScript%22%3A%22%2Fopt%2Fatom%2Fresources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fopt%2Fatom%2Fresources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.176.0%22%2C%22shellLoadTime%22%3A265%7D:1

SyntaxError: Unexpected string
  at Object.parse (native)
  at /home/matttbe/.atom/packages/save-session/lib/files.coffee:12:26
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)
  at Ipc.sendSync (/opt/atom/resources/atom/renderer/api/lib/ipc.js:39:29)
  at BrowserWindow.RemoteMemberFunction [as getPosition] (/opt/atom/resources/atom/renderer/api/lib/remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (/opt/atom/resources/app/src/atom.js:498:29)
  at Object.module.exports.save (/home/matttbe/.atom/packages/save-session/lib/dimensions.coffee:22:19)
  at /home/matttbe/.atom/packages/save-session/lib/dimensions.coffee:44:32
  at handler (/opt/atom/resources/app/src/space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at elemData.handle (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "autocomplete-clang",
      "linter-pylint"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "save-session": {
    "project": "/home/matttbe/Documents/SINF/SINF22MS/Thesis/pcap-measurement",
    "windowX": 0,
    "windowY": 24,
    "windowWidth": 1366,
    "windowHeight": 768,
    "dataSaveFolder": "/home/matttbe/.atom/packages/save-session/projects"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.0.10
linter, v0.11.1
linter-pyflakes, v0.0.4
minimap, v4.0.1
monokai, v0.12.0
save-session, v0.11.3

# Dev
No dev packages
```

**Comment by mpeterson2** [comment]
Not really sure what could have caused this, but it may be related to #54.

**Comment by gerane** [comment]
This happens for me even without closing tabs.

**Comment by mpeterson2** [comment]
Closing old issues that are probably irrelevant to the code just to clear up the clutter. Go ahead and open a new issue if there is still a problem.
