### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by raddevon** [mpeterson2/save-session#60]
Just got this error after closing one window with a project in it and then quitting Atom with another window remaining with a project and four files open in it. I immediately restarted Atom and got this error again. If I disable and re-enable the package, that also triggers the error.

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.1
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.11.3

### Stack Trace

Uncaught SyntaxError: Unexpected token <

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html?loadSettings=%7B%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.177.0%22%2C%22shellLoadTime%22%3A252%7D:1

SyntaxError: Unexpected token <
  at Object.parse (native)
  at /Users/raddevon/.atom/packages/save-session/lib/files.coffee:12:26
  at fs.js:337:14
  at FSReqWrap.oncomplete (fs.js:100:15)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as getPosition] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom.js:505:29)
  at Object.module.exports.save (/Users/raddevon/.atom/packages/save-session/lib/dimensions.coffee:22:19)
  at /Users/raddevon/.atom/packages/save-session/lib/dimensions.coffee:44:32
  at handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "enlightened"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".hg"
    ]
  },
  "save-session": {
    "dataSaveFolder": "/Users/raddevon/.atom/packages/save-session/projects",
    "project": "/Users/raddevon/Documents/projects/microscope",
    "windowX": 0,
    "windowY": 23,
    "windowWidth": 1440,
    "windowHeight": 2537
  }
}
```

### Installed Packages

```coffee
# User
Search, v0.4.0
achievements, v0.7.0
angularjs, v0.1.0
atom-handlebars, v0.4.0
auto-update-packages, v0.2.2
autocomplete-paths, v1.0.1
autocomplete-plus, v2.0.11
autocomplete-snippets, v1.0.0
color-picker, v1.4.4
compass, v0.7.5
css-color-highlighting, v0.2.4
emmet, v2.3.3
enlightened, v0.2.4
highlight-line, v0.9.3
javascript-snippets, v1.0.0
language-spacebars, v0.2.2
linter, v0.11.1
linter-coffeelint, v0.1.7
linter-csslint, v0.0.11
linter-haml, v0.1.0
linter-handlebars, v0.1.1
linter-htmlhint, v0.0.8
linter-jshint, v0.1.0
linter-php, v0.0.11
meteor-api, v2.12.0
minimap, v4.0.2
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
project-manager, v1.15.5
save-session, v0.11.3
set-syntax, v0.2.0
seti-ui, v0.6.3
tab-smart-sort, v0.1.2
travis-ci-status, v0.11.2
white-cursor, v0.5.2
wordpress, v0.2.0
zentabs, v0.6.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by mpeterson2** [comment]
Probably related to #54.

**Comment by mpeterson2** [comment]
Closing old issues that are probably irrelevant to the code just to clear up the clutter. Go ahead and open a new issue if there is still a problem.
