### ISSUE TITLE
Uncaught SyntaxError: Unexpected token c

### ISSUE THREAD

**Issue by panw** [mpeterson2/save-session#61]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.11.3

### Stack Trace

Uncaught SyntaxError: Unexpected token c

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html?loadSettings=%7B%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.176.0%22%2C%22shellLoadTime%22%3A249%7D:1

SyntaxError: Unexpected token c
  at Object.parse (native)
  at /Users/panw/.atom/packages/save-session/lib/files.coffee:12:26
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)
  at Ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:39:29)
  at BrowserWindow.RemoteMemberFunction [as getSize] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom.js:499:29)
  at Object.module.exports.save (/Users/panw/.atom/packages/save-session/lib/dimensions.coffee:22:19)
  at /Users/panw/.atom/packages/save-session/lib/dimensions.coffee:44:32
  at handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  },
  "save-session": {
    "project": "/Users/panw/panlist",
    "windowX": 122,
    "windowY": 23,
    "windowWidth": 1157,
    "windowHeight": 773,
    "dataSaveFolder": "/Users/panw/.atom/packages/save-session/projects"
  }
}
```

### Installed Packages

```coffee
# User
save-session, v0.11.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by mpeterson2** [comment]
Closing old issues that are probably irrelevant to the code just to clear up the clutter. Go ahead and open a new issue if there is still a problem.
