### ISSUE TITLE
Uncaught SyntaxError: Unexpected token v

### ISSUE THREAD

**Issue by madeofpeople** [mpeterson2/save-session#69]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.11.5

### Stack Trace

Uncaught SyntaxError: Unexpected token v

```
At file:///Users/thiago/Downloads/Atom.app/Contents/Resources/app/static/index.html?loadSettings=%7B%22bootstrapScript%22%3A%22%2FUsers%2Fthiago%2FDownloads%2FAtom.app%2FContents%2FResources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FUsers%2Fthiago%2FDownloads%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.169.0%22%2C%22shellLoadTime%22%3A5074%7D:1

SyntaxError: Unexpected token v
  at Object.parse (native)
  at /Users/thiago/.atom/packages/save-session/lib/files.coffee:12:26
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)
  at Ipc.sendSync (/Users/thiago/Downloads/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:39:29)
  at BrowserWindow.RemoteMemberFunction [as getPosition] (/Users/thiago/Downloads/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (/Users/thiago/Downloads/Atom.app/Contents/Resources/app/src/atom.js:500:29)
  at Object.module.exports.save (/Users/thiago/.atom/packages/save-session/lib/dimensions.coffee:22:19)
  at /Users/thiago/.atom/packages/save-session/lib/dimensions.coffee:44:32
  at handler (/Users/thiago/Downloads/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (/Users/thiago/Downloads/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at elemData.handle (/Users/thiago/Downloads/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  },
  "save-session": {
    "restoreOpenFiles": false,
    "restoreOpenFileContents": false,
    "restoreOpenFilesPerProject": false,
    "restoreCursor": false,
    "restoreScrollPosition": false,
    "project": "/Users/thiago/kalabox/www/pe-blog/wp-content/themes/pinnacle",
    "windowX": 156,
    "windowY": 23,
    "windowWidth": 1280,
    "windowHeight": 877,
    "treeSize": 173,
    "dataSaveFolder": "/Users/thiago/.atom/packages/save-session/projects"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.6
recent-files, v0.3.0
save-session, v0.11.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by mpeterson2** [comment]
Closing old issues that are probably irrelevant to the code just to clear up the clutter. Go ahead and open a new issue if there is still a problem.
