### ISSUE TITLE
Uncaught SyntaxError: Unexpected token W

### ISSUE THREAD

**Issue by Seidr** [mpeterson2/save-session#72]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: linux 3.13.0-45-generic
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.11.5

### Stack Trace

Uncaught SyntaxError: Unexpected token W

```
At file:///usr/share/atom/resources/app/static/index.html?loadSettings=%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2Fhome%2Fjamesh%2FDevelopment%2Fwebsites%2Ftest.site%22%7D%5D%2C%22bootstrapScript%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.182.0%22%2C%22initialPaths%22%3A%5B%22%2Fhome%2Fjamesh%2FDevelopment%2Fwebsites%2Ftest.site%22%5D%7D:1

SyntaxError: Unexpected token W
  at Object.parse (native)
  at /home/jamesh/.atom/packages/save-session/lib/files.coffee:12:26
  at fs.js:337:14
  at FSReqWrap.oncomplete (fs.js:100:15)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as getSize] (/usr/share/atom/resources/atom/renderer/api/lib/remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (/usr/share/atom/resources/app/src/atom.js:515:29)
  at Object.module.exports.save (/home/jamesh/.atom/packages/save-session/lib/dimensions.coffee:22:19)
  at /home/jamesh/.atom/packages/save-session/lib/dimensions.coffee:44:32
  at handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {},
  "save-session": {
    "dataSaveFolder": "/home/jamesh/.atom/packages/save-session/projects",
    "project": "/home/jamesh/Development/websites/test.site",
    "windowX": 49,
    "windowY": 24,
    "windowWidth": 1871,
    "windowHeight": 1056,
    "treeSize": 504
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.3.1
project-manager, v1.15.5
save-session, v0.11.5

# Dev
No dev packages
```

**Comment by mpeterson2** [comment]
Closing old issues that are probably irrelevant to the code just to clear up the clutter. Go ahead and open a new issue if there is still a problem.
