### ISSUE TITLE
Uncaught SyntaxError: Unexpected token t

### ISSUE THREAD

**Issue by edwardhew** [mpeterson2/save-session#82]
[Enter steps to reproduce below:]

1. Updated to 0.12
2. Restarted Atom manually.

**Atom Version**: 0.179.0
**System**: Microsoft Windows 8.1
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.12.0

### Stack Trace

Uncaught SyntaxError: Unexpected token t

```
At file:///C:/Users/Edward/AppData/Local/atom/app-0.179.0/resources/app/static/index.html?loadSettings=%7B%22pathToOpen%22%3Anull%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5CEdward%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.179.0%5C%5Cresources%5C%5Capp%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5CEdward%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.179.0%5C%5Cresources%5C%5Capp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.179.0%22%2C%22shellLoadTime%22%3A432%2C%22initialPath%22%3Anull%7D:1

SyntaxError: Unexpected token t
  at Object.parse (native)
  at C:\Users\Edward\.atom\packages\save-session\lib\files.coffee:12:26
  at fs.js:337:14
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-toml",
      "metrics",
      "language-ruby-on-rails",
      "language-perl",
      "language-go",
      "language-coffee-script",
      "language-clojure"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "save-session": {
    "dataSaveFolder": "C:\\Users\\Edward\\.atom\\packages\\save-session\\projects",
    "project": "D:\\Localhost\\www\\edwardhew_v2",
    "windowX": -8,
    "windowY": -8,
    "windowWidth": 1296,
    "windowHeight": 1010,
    "restoreCursor": false,
    "restoreOpenFiles": false,
    "restoreOpenFileContents": false,
    "restoreFileTreeSize": false,
    "restoreOpenFilesPerProject": false,
    "restoreScrollPosition": false,
    "restoreWindow": false,
    "skipSavePrompt": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.2.0
color-picker, v1.4.4
less-autocompile, v1.0.0
save-session, v0.12.0

# Dev
No dev packages
```

Btw another issue and the reason I have most options disabled is that save-session will reopen a lot more files than I had open, I think its because I opened those files at some point during the last session.

**Comment by mpeterson2** [comment]
Closing old issues that are probably irrelevant to the code just to clear up the clutter. Go ahead and open a new issue if there is still a problem.
