### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by mjrev** [mpeterson2/save-session#83]
**Steps to reproduce:**

1. Open developer tools
2. Delete atom-workspace block
3. Close atom

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.12.0

### Stack Trace

Uncaught SyntaxError: Unexpected token .

```
At file:///C:/Users/Constantine/AppData/Local/atom/app-0.187.0/resources/app/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5CConstantine%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.187.0%5C%5Cresources%5C%5Capp%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5CConstantine%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.187.0%5C%5Cresources%5C%5Capp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.187.0%22%2C%22shellLoadTime%22%3A1287%2C%22initialPaths%22%3A%5B%22D%3A%5C%5CCopy%5C%5Cprojects%5C%5Ckate%5C%5Cmixture%22%5D%7D:1

SyntaxError: Unexpected token .
  at Object.parse (native)
  at C:\Users\Constantine\.atom\packages\save-session\lib\files.coffee:12:26
  at fs.js:337:14
  at FSReqWrap.oncomplete (fs.js:100:15)
  at EventEmitter.ipc.sendSync (C:\Users\Constantine\AppData\Local\atom\app-0.187.0\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as getSize] (C:\Users\Constantine\AppData\Local\atom\app-0.187.0\resources\atom.asar\renderer\api\lib\remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (C:\Users\Constantine\AppData\Local\atom\app-0.187.0\resources\app\src\atom.js:520:29)
  at Object.module.exports.save (C:\Users\Constantine\.atom\packages\save-session\lib\dimensions.coffee:23:19)
  at C:\Users\Constantine\.atom\packages\save-session\lib\dimensions.coffee:49:32
  at handler (C:\Users\Constantine\AppData\Local\atom\app-0.187.0\resources\app\src\space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (C:\Users\Constantine\AppData\Local\atom\app-0.187.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at elemData.handle (C:\Users\Constantine\AppData\Local\atom\app-0.187.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "monokai"
    ],
    "disabledPackages": [
      "compare-files",
      "select-rectangle",
      "selection-count"
    ]
  },
  "save-session": {
    "dataSaveFolder": "C:\\Users\\Constantine\\.atom\\packages\\save-session\\projects",
    "windowX": -8,
    "windowY": -8,
    "windowWidth": 1382,
    "windowHeight": 744,
    "project": "D:\\Copy\\projects\\kate\\mixture",
    "treeSize": 189,
    "fullScreen": false
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
color-picker, v1.4.4
emmet, v2.3.4
file-icons, v1.5.1
highlight-selected, v0.9.1
isotope-ui, v1.6.2
linter, v0.12.0
minimap, v4.6.0
minimap-highlight-selected, v4.2.0
monokai, v0.12.0
project-manager, v1.15.5
save-session, v0.12.0
Sublime-Style-Column-Selection, v1.2.3

# Dev
No dev packages
```

**Comment by mpeterson2** [comment]
Closing old issues that are probably irrelevant to the code just to clear up the clutter. Go ahead and open a new issue if there is still a problem.
